### ISSUE TITLE
/mentor endpoint doesnt match README docs

### ISSUE THREAD

**Issue by marktai** [ucladevx/BQuest-Backend#42]
title

**Comment by DavidWChen** [comment]
Is the missing bio field and the date field the only parts that don't match? (I added bio in the screenshot) It seems to match otherwise.
![screen shot 2018-01-24 at 5 10 41 pm](https://user-images.githubusercontent.com/23110056/35365502-ca1bc568-0129-11e8-92ea-477299aeaa70.png)

**Comment by marktai** [comment]
*mentors. the one that lists the results of the search
