### ISSUE TITLE
Ordering of autofill on search

### ISSUE THREAD

**Issue by lineaba** [ucladevx/BQuest-Backend#60]
Currently we do not get most ideal ordering of autocomplete suggestions, when a user searches for ambassadors.
Currently results come back in alphabetic ordering, but I believe it would be better to sort them in "Closest match" comparing strings from right to left first? I.e. Linguistics is a closer match to the query "linguistics" than is Asian Languages and Linguistics. A user looking for that would probably start by typing "Asia......"
![image](https://user-images.githubusercontent.com/32916783/38528799-027df4c2-3c16-11e8-8ec0-e3188fba2a5c.png)

**Comment by DavidWChen** [comment]
On hold since we're revamping the search.

**Comment by DavidWChen** [comment]
#75 Search now works differently and there is no autofill on front-end
