### ISSUE TITLE
Algorithm for Search Recommendations

### ISSUE THREAD

**Issue by DavidWChen** [ucladevx/BQuest-Backend#85]

**Comment by GiovanniMoya** [comment]
tasks: 

add profile bio search in alg.

research how to relate topics of interest to majors 

add table for high level filtering ("topic of interest") - make separate JSON file 

report time: 

sometime during week

**Comment by Cscotttaakan** [comment]
"Finish Unit Testing"
Possibly iterative test cases or manual entry

**Comment by DavidWChen** [comment]
#94
